[build]
    functions = "functions"
[[redirects]]
  from = "/api/registrations"
  to = "http://44.202.147.131:3000/api/registrations"
  status = 200

  [[redirects]]
  from = "/api/register"
  to = "http://44.202.147.131:3000/api/register"
  status = 200